-- Premium social-feed continuity (2026-09-01): one truthful context label per post and a genuine
-- activity inbox. Activity rows are generated by authenticated social writes; the client never
-- fabricates them. Pulls are repeatable so every signed-in device can build the same local inbox,
-- deduping by immutable event id.

alter table public.posts
  add column if not exists earned_context text;

create table if not exists public.social_activity (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('respect', 'comment', 'follow')),
  actor_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  post_id uuid references public.posts(id) on delete cascade,
  comment_id uuid references public.comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  check (actor_id <> recipient_id)
);

create index if not exists social_activity_recipient_created
  on public.social_activity (recipient_id, created_at desc);
create index if not exists social_activity_created
  on public.social_activity (created_at);
create unique index if not exists social_activity_source_unique
  on public.social_activity (
    kind, actor_id, recipient_id,
    coalesce(post_id, '00000000-0000-0000-0000-000000000000'::uuid),
    coalesce(comment_id, '00000000-0000-0000-0000-000000000000'::uuid)
  );

alter table public.social_activity enable row level security;
-- No direct client policies. The bounded definer RPC below exposes only the caller's rows.

create or replace function public.capture_reaction_activity()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare recipient uuid;
begin
  select p.author_id into recipient from public.posts p where p.id = new.post_id;
  if recipient is not null and recipient <> new.user_id then
    insert into public.social_activity (kind, actor_id, recipient_id, post_id, created_at)
    values ('respect', new.user_id, recipient, new.post_id, new.created_at)
    on conflict do nothing;
  end if;
  return new;
end;
$$;

create or replace function public.capture_comment_activity()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare recipient uuid;
begin
  select p.author_id into recipient from public.posts p where p.id = new.post_id;
  if recipient is not null and recipient <> new.author_id then
    insert into public.social_activity
      (kind, actor_id, recipient_id, post_id, comment_id, created_at)
    values ('comment', new.author_id, recipient, new.post_id, new.id, new.created_at)
    on conflict do nothing;
  end if;
  return new;
end;
$$;

create or replace function public.capture_follow_activity()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.social_activity (kind, actor_id, recipient_id, created_at)
  values ('follow', new.follower_id, new.followee_id, new.created_at)
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists reactions_activity_insert on public.reactions;
create trigger reactions_activity_insert after insert on public.reactions
  for each row execute function public.capture_reaction_activity();

drop trigger if exists comments_activity_insert on public.comments;
create trigger comments_activity_insert after insert on public.comments
  for each row execute function public.capture_comment_activity();

drop trigger if exists follows_activity_insert on public.follows;
create trigger follows_activity_insert after insert on public.follows
  for each row execute function public.capture_follow_activity();

create or replace function public.pull_social_activity(p_limit int default 100)
returns table (
  id uuid,
  kind text,
  actor_handle text,
  actor_name text,
  post_id uuid,
  post_title text,
  comment_body text,
  created_at timestamptz
)
language plpgsql security definer set search_path = public
as $$
declare me uuid := (select auth.uid());
begin
  if me is null then return; end if;
  return query
    select a.id, a.kind, p.handle, p.display_name,
           a.post_id, post.title, c.body, a.created_at
      from public.social_activity a
      join public.profiles p on p.id = a.actor_id
      left join public.posts post on post.id = a.post_id
      left join public.comments c on c.id = a.comment_id
     where a.recipient_id = me
       and a.created_at >= now() - interval '30 days'
       and not public.is_blocked_either(me, a.actor_id)
     order by a.created_at desc
     limit least(greatest(coalesce(p_limit, 100), 1), 100);
end;
$$;

revoke all on function public.pull_social_activity(int) from public;
grant execute on function public.pull_social_activity(int) to authenticated;

-- Retention is maintenance, not read-path work. The former RPC deleted globally-expired rows on
-- every athlete's inbox refresh, turning a read into a table write/lock at social scale. A bounded
-- service-only function runs daily when pg_cron is available; otherwise the deployment scheduler
-- can invoke the same function without exposing it to clients.
create or replace function public.prune_social_activity_retention()
returns bigint
language plpgsql security definer set search_path = public
as $$
declare removed bigint;
begin
  delete from public.social_activity where created_at < now() - interval '90 days';
  get diagnostics removed = row_count;
  return removed;
end;
$$;

revoke all on function public.prune_social_activity_retention() from public;
grant execute on function public.prune_social_activity_retention() to service_role;

do $schedule$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule(
      'momentum-social-activity-retention',
      '17 3 * * *',
      'select public.prune_social_activity_retention();'
    );
  end if;
exception
  when undefined_function or invalid_schema_name or insufficient_privilege then
    null; -- service scheduler can call the function when pg_cron is unavailable here
end
$schedule$;

-- Append earned_context after cover_is_photo. Name-based JSON decoding keeps older app builds
-- compatible, while new clients gracefully treat the absent field as nil before this migration.
drop function if exists public.feed_page(text, timestamptz, uuid, int, uuid);
create or replace function public.feed_page(
  p_scope text default 'everyone',
  p_cursor_created timestamptz default null,
  p_cursor_id uuid default null,
  p_limit int default 20,
  p_author uuid default null
)
returns table (
  id uuid,
  author_id uuid,
  author_name text,
  author_handle text,
  author_location text,
  avatar_path text,
  workout_type text,
  started_at timestamptz,
  title text,
  caption text,
  stat_line text,
  pr_badge text,
  muscles jsonb,
  route jsonb,
  map_style text,
  ai_read text,
  photo_paths text[],
  reaction_count bigint,
  viewer_reacted boolean,
  created_at timestamptz,
  author_pro boolean,
  comment_count bigint,
  cover_is_photo boolean,
  earned_context text
)
language sql stable security invoker set search_path = public
as $$
  select
    p.id, p.author_id, pr.display_name, nullif(pr.handle, ''), pr.public_location,
    pr.avatar_path, p.workout_type, p.started_at, p.title, p.caption, p.stat_line,
    p.pr_badge, p.muscles, p.route, p.map_style, p.ai_read, p.photo_paths,
    (select count(*) from reactions r
      where r.post_id = p.id and not is_blocked_either((select auth.uid()), r.user_id)),
    exists (select 1 from reactions r
      where r.post_id = p.id and r.user_id = (select auth.uid())),
    p.created_at, pr.is_pro,
    (select count(*) from comments c
      where c.post_id = p.id and not is_blocked_either((select auth.uid()), c.author_id)),
    p.cover_is_photo, p.earned_context
  from posts p
  join profiles pr on pr.id = p.author_id
  where (p_scope <> 'following'
         or p.author_id = (select auth.uid())
         or is_following((select auth.uid()), p.author_id))
    and (p_author is null or p.author_id = p_author)
    and (p_cursor_created is null
         or (p.created_at, p.id) < (p_cursor_created, p_cursor_id))
  order by p.created_at desc, p.id desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
$$;
